### ISSUE TITLE
rebuild in React / TypeScript

### ISSUE THREAD

**Issue by relandboyle** [rboyle-software/interview-skills-grid#3]

**Comment by xeonstaff** [comment]
could potentially help with this; the prototype on Heroku isn't working tho? I'd love to see what it looks like to see if I could help

**Comment by relandboyle** [comment]
@xeonstaff Hi Joel. Thanks for reaching out.

Will you please clarify "_the prototype on Heroku isn't working tho?_" as the deployed app is working as far as I know.

There's a separate repo for the React version of this app.
